[app]

# (str) Title of your application
title = My Kivy App

# (str) Package name
package.name = mykivyapp

# (str) Package domain (needed for android packaging)
package.domain = org.test

# (list) Source files to include (let it specify .py and other assets)
source.dir = .

# (list) Source files to include (let it specify .py and other assets)
source.include_exts = py,png,jpg,kv,atlas

# (list) Application version
version = 0.1

# (list) Application requirements
# comma separated e.g. requirements = sqlite3,kivy
requirements = python3,kivy

# (list) Custom source folders for requirements
#requirements.source_dirs = =

# (list) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (list) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientations
orientation = portrait

# (list) List of exclusions
#osx.python_version = 3
#osx.kivy_version = 1.9.1

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 0

# (string) Presplash background color (color format #RRGGBB or #AARRGGBB)
#presplash.background_color = #FFFFFF

# (list) Permissions
android.permissions = INTERNET

# (int) Target Android API, should be as high as possible
android.api = 33

# (int) Minimum API your APK will support
android.minapi = 24

# (str) Android NDK version to use
android.ndk = 25b

# (bool) Use adb to pull/push files on target device
#android.adb_args = 

# (list) The format used to package the app for store (aab or apk or aab,apk)
android.archs = arm64-v8a, armeabi-v7a

# (bool) Enable Android auto-backup (default True)
android.allow_backup = True

[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = Debug, 2 = Info)
warn_on_root = 1

# (str) Path to build artifact storage, absolute or relative to spec file
#bin_dir = ./bin

# (str) Path to build output (internal to buildozer)
#build_dir = ./.buildozer

# (str) Path to Python for android (p4a)
#p4a.source_dir = 

# (str) The branch of p4a to use
#p4a.branch = master
